<script lang="ts">
	import { enhance } from '$app/forms';
	import { page } from '$app/stores';
	import { fullName, record, records } from '$lib/api';
	import { t } from '$lib/i18n';
	let { data, form }: any = $props();
	let locale = $derived(data.locale ?? 'en');
	let path = $derived(data.path ?? '/');
	let resource = $derived(record(data.resource) ?? data.resource);
	let failure = $derived(form?.error ?? data.error);
	const tr = (key: string) => t(locale, key);
	const list = $derived(records(data.resource));
	const user = $derived(data.user);
	const profile = (value: any) => value?.expand?.user ?? value?.user ?? value;
	const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
	const fmtDate = (value?: string) => value ? new Intl.DateTimeFormat(locale, { dateStyle: 'medium' }).format(new Date(value)) : '—';
	const recordsOf = (value: any) => records(value);
	const pageCount = (value: any, fallback = 5) => Math.max(1, Number(value?.total_pages ?? Math.ceil(Number(value?.total ?? 0) / Number(value?.per_page ?? fallback))));
	const getResourceItems = (value: any) => records(value?.items);
	const queryValue = (key: string) => $page.url.searchParams.get(key) ?? '';
	const planType = (value: any) => $page.url.searchParams.get('plan_type') ?? value?.plan_type ?? value?.type ?? 'training';
	const arrayValue = (value: any) => Array.isArray(value) ? value : [];
	function confirmDelete(event: SubmitEvent) {
		if (!window.confirm('Delete this record? This cannot be undone.')) event.preventDefault();
	}
	function textValue(value: any, key: string) { return value?.[key] ?? ''; }
	function metrics(value: any) {
		const source = value?.stats ?? value?.overall ?? value ?? {};
		if (!source || typeof source !== 'object') return [];
		return Object.entries(source).filter(([, item]) => typeof item === 'number' || typeof item === 'string').slice(0, 8);
	}
</script>

<svelte:head>
	<title>{path === '/login' ? `${tr('Log in')} · ${data.tenantName ?? 'Gyme'}` : `${label(path.split('/').filter(Boolean).at(-1) ?? 'Dashboard')} · ${data.tenantName ?? 'Gyme'}`}</title>
</svelte:head>

{#if path === '/login'}
	<section class="login-layout">
		<div class="login-art"><span class="art-kicker">{data.tenantName ?? 'GYME'} / COACHING SYSTEM</span><h1>Strength<br />in the<br /><em>details.</em></h1><p>Better coaching starts with a clearer picture.</p><span class="art-orbit" aria-hidden="true"></span></div>
		<div class="login-form-wrap">
			<a class="brand brand-dark" href="/login">{#if data.tenantLogo}<img class="brand-logo" src={data.tenantLogo} alt="" />{:else}<span class="brand-mark">G</span>{/if}<span>{data.tenantName ?? 'GYME'}</span></a>
			<div class="form-heading"><span class="eyebrow">YOUR TRAINING, IN SYNC</span><h2>{tr('Welcome back')}</h2><p>Sign in to continue to your coaching space.</p></div>
			{#if failure}<div class="notice error" role="alert">{failure}</div>{/if}
			<form method="POST" action="?/login" use:enhance class="form-stack">
				<label>{tr('Email')}<input type="text" name="identity" autocomplete="username" required maxlength="254" placeholder="name@example.com" /></label>
				<label>{tr('Password')}<input type="password" name="password" autocomplete="current-password" required maxlength="128" /></label>
				<input type="hidden" name="next" value={$page.url.searchParams.get('next') ?? ''} />
				<button class="button primary wide" type="submit">{tr('Log in')} <span aria-hidden="true">↗</span></button>
			</form>
			<p class="form-note">Your gym workspace is private to your team.</p>
		</div>
	</section>
{:else if path === '/change-password'}
	<section class="page narrow">
		<a class="backlink" href="/profile">← {tr('Profile')}</a><div class="page-heading"><span class="eyebrow">ACCOUNT SECURITY</span><h1>{tr('Change password')}</h1></div>
		{#if failure}<div class="notice error" role="alert">{failure}</div>{/if}
		<form method="POST" action="?/changePassword" use:enhance class="form-stack panel"><input type="hidden" name="role" value={user?.role ?? ''} />
			<label>{tr('Current password')}<input type="password" name="old_password" required autocomplete="current-password" /></label>
			<label>{tr('New password')}<input type="password" name="new_password" required minlength="8" maxlength="72" autocomplete="new-password" /></label>
			<label>{tr('Confirm password')}<input type="password" name="confirm_password" required minlength="8" maxlength="72" autocomplete="new-password" /></label>
			<button class="button primary" type="submit">{tr('Save changes')}</button>
		</form>
	</section>
{:else if failure}
	<section class="page state-page"><span class="state-mark">!</span><h1>{tr('Server unavailable')}</h1><p>{failure}</p><a class="button primary" href={path}>{tr('Try again')}</a></section>
{:else if path === '/dashboard' || path === '/dashboard/coach-stats'}
	<section class="page">
		<div class="page-heading split"><div><span class="eyebrow">{user?.role === 'coach' ? 'COACH WORKSPACE' : 'GYM OVERVIEW'}</span><h1>{tr('Overall statistics')}</h1><p>{tr('Welcome back')}{user?.first_name ? `, ${user.first_name}` : ''}.</p></div>
			<form method="GET" action="/dashboard" class="select-inline"><label for="timeframe">{tr('Time period')}</label><select id="timeframe" name="timeframe" value={queryValue('timeframe') || 'all'} onchange={(event) => event.currentTarget.form?.requestSubmit()}><option value="all">{tr('All time')}</option><option value="month">{tr('This month')}</option><option value="week">{tr('This week')}</option></select></form>
		</div>
		<div class="metric-grid">{#each metrics(resource?.stats ?? resource) as [key, value]}<article class="metric"><span>{label(String(key))}</span><strong>{value}</strong></article>{:else}<p class="empty wide-empty">{tr('No records yet')}</p>{/each}</div>
		{#if path === '/dashboard/coach-stats'}<div class="records-list">{#each recordsOf(resource) as coach}<a class="person-row" href={coach.id ? `/coaches/${coach.id}` : '/dashboard'}><span class="person-mark">{fullName(coach).slice(0, 1)}</span><span class="person-main"><strong>{fullName(coach)}</strong><small>{coach.plan_count ?? 0} {tr('Plans')} · {coach.active_plans ?? 0} {tr('Active')}</small></span><span class="row-arrow">↗</span></a>{:else}<div class="empty">{tr('No records yet')}</div>{/each}</div>{/if}
		{#if user?.role === 'owner' && Array.isArray(resource?.coach_stats)}
			<div class="section-heading"><h2>{tr('Coach statistics')}</h2><a href="/coaches">{tr('Manage coaches')} ↗</a></div><div class="table-wrap"><table><thead><tr><th>{tr('Coach')}</th><th>{tr('Plans')}</th><th>{tr('Trainees')}</th><th>{tr('Status')}</th></tr></thead><tbody>{#each resource.coach_stats as coach}<tr><td><a href={`/coaches/${coach.id}`}>{fullName(coach)}</a></td><td>{coach.plan_count ?? '—'}</td><td>{coach.trainee_count ?? '—'}</td><td>{coach.active_plans ?? '—'}</td></tr>{/each}</tbody></table></div>
		{/if}
		{#if path === '/dashboard' && user?.role === 'owner'}<div class="shortcut-row"><a class="shortcut" href="/trainees"><span>01</span><strong>{tr('All trainees')}</strong><small>Review and update your roster</small></a><a class="shortcut" href="/coaches"><span>02</span><strong>{tr('Manage coaches')}</strong><small>Team access and assignments</small></a><a class="shortcut" href="/plans"><span>03</span><strong>{tr('Plans')}</strong><small>Programs and reusable templates</small></a></div>{/if}
	</section>
{:else if path === '/trainees' || path === '/trainees/search' || path === '/trainees/filter'}
	<section class="page">
		<div class="page-heading split"><div><span class="eyebrow">PEOPLE / ROSTER</span><h1>{tr('Trainees')}</h1><p>{data.resource?.total ?? list.length} athletes in your coaching space</p></div><a class="button primary" href="/trainees/new">＋ {tr('Add trainee')}</a></div>
		<form class="filter-bar" method="GET" action="/trainees/search"><label class="search-field"><span aria-hidden="true">⌕</span><input name="query" value={queryValue('query')} placeholder={`${tr('Search')} by name or email`} /></label><select name="gender" aria-label={tr('Gender')} value={queryValue('gender')}><option value="">{tr('Gender')} · All</option><option value="male">Male</option><option value="female">Female</option></select><select name="status" aria-label={tr('Status')} value={queryValue('status')}><option value="">{tr('Status')} · All</option><option value="active">{tr('Active')}</option><option value="inactive">{tr('Inactive')}</option></select><label class="date-filter">{tr('Born after')}<input type="date" name="min_birthdate" value={queryValue('min_birthdate')} /></label><label class="date-filter">{tr('Born before')}<input type="date" name="max_birthdate" value={queryValue('max_birthdate')} /></label><button class="button outline" type="submit">{tr('Filter')}</button></form>
		<div class="records-list">{#each list as trainee (trainee.id)}{@const person = profile(trainee)}<a class="person-row" href={`/trainees/${trainee.id}`}><span class="person-mark">{fullName(person).slice(0, 1)}</span><span class="person-main"><strong>{fullName(person)}</strong><small>{person?.email ?? '—'} · {person?.phone ?? 'No phone'}</small></span><span class="row-meta">{trainee.gender ?? '—'}</span><span class:tag-active={trainee.status === 'active'} class="tag">{trainee.status ?? '—'}</span><span class="row-arrow">↗</span></a>{:else}<div class="empty">{tr('No records yet')}<a href="/trainees/new">{tr('Create account')}</a></div>{/each}</div>
		{#if pageCount(data.resource) > 1}<nav class="pagination"><span>{data.resource?.total ?? list.length} records</span><div>{#each Array.from({ length: pageCount(data.resource) }, (_, i) => i + 1) as current}<a class:current={current === Number(queryValue('page') || 1)} href={`?${new URLSearchParams({ ...Object.fromEntries($page.url.searchParams), page: String(current) })}`}>{current}</a>{/each}</div></nav>{/if}
	</section>
{:else if /^\/trainees\/new$/.test(path) || /^\/trainees\/[^/]+\/edit$/.test(path)}
	{@const editing = path !== '/trainees/new'}{@const trainee = editing ? resource : null}{@const person = profile(trainee)}
	<section class="page narrow"><a class="backlink" href={editing ? `/trainees/${trainee?.id}` : '/trainees'}>← {tr('Trainees')}</a><div class="page-heading"><span class="eyebrow">PEOPLE / RECORD</span><h1>{editing ? tr('Edit trainee') : tr('New trainee')}</h1><p>Set up contact details and useful training context.</p></div>
		{#if failure}<div class="notice error" role="alert">{failure}</div>{/if}
		<form method="POST" action="?/submit" use:enhance class="form-stack panel">
			<div class="two-col"><label>{tr('First name')}<input name="first_name" required maxlength="50" value={person?.first_name ?? ''} /></label><label>{tr('Last name')}<input name="last_name" required maxlength="50" value={person?.last_name ?? ''} /></label></div>
			<label>{tr('Email')}<input name="email" type="email" required value={person?.email ?? ''} readonly={editing} /></label><div class="two-col"><label>{tr('Phone')}<input name="phone" type="tel" value={person?.phone ?? ''} /></label><label>{tr('Birth date')}<input name="birthdate" type="date" value={trainee?.birthdate?.slice(0, 10) ?? ''} /></label></div>
			<div class="two-col"><label>{tr('Gender')}<select name="gender" value={trainee?.gender ?? ''}><option value="">—</option><option value="male">Male</option><option value="female">Female</option></select></label><label>{tr('Blood type')}<select name="blood_type" value={trainee?.blood_type ?? ''}><option value="">Unknown</option>{#each ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'] as blood}<option>{blood}</option>{/each}</select></label></div>
			{#each [['training_history', 'Training history'], ['steroid_history', 'Supplement history'], ['limitations', 'Limitations and health notes'], ['notes', 'Notes']] as [name, title]}<label>{title}<textarea name={name} rows="3" maxlength="2000">{trainee?.[name] ?? ''}</textarea></label>{/each}
			<div class="form-actions"><a class="button outline" href={editing ? `/trainees/${trainee?.id}` : '/trainees'}>{tr('Cancel')}</a>{#if editing}<button class="button danger" type="submit" name="intent" value="delete" formaction="?/submit" onclick={(event) => { if (!window.confirm('Delete this trainee? This cannot be undone.')) event.preventDefault(); }}>{tr('Delete')}</button>{/if}<button class="button primary" type="submit">{editing ? tr('Save changes') : tr('Save')}</button></div>
		</form>
	</section>
{:else if /^\/trainees\/[^/]+$/.test(path)}
	{@const trainee = resource}{@const person = profile(trainee)}
	<section class="page"><a class="backlink" href="/trainees">← {tr('Trainees')}</a><div class="detail-heading"><span class="person-mark large">{fullName(person).slice(0, 1)}</span><div><span class="eyebrow">TRAINEE PROFILE</span><h1>{fullName(person)}</h1><p>{person?.email} {person?.phone ? ` · ${person.phone}` : ''}</p></div><a class="button outline" href={`/trainees/${trainee?.id}/edit`}>{tr('Edit')}</a></div>
		<div class="detail-grid"><article class="panel"><span class="eyebrow">ABOUT</span><dl><dt>{tr('Gender')}</dt><dd>{trainee?.gender ?? '—'}</dd><dt>{tr('Birth date')}</dt><dd>{fmtDate(trainee?.birthdate)}</dd><dt>{tr('Blood type')}</dt><dd>{trainee?.blood_type ?? '—'}</dd><dt>{tr('Height')} / {tr('Weight')}</dt><dd>{trainee?.height ?? '—'} / {trainee?.weight ?? '—'}</dd></dl>{#each ['training_history', 'steroid_history', 'supplement_history', 'limitations', 'notes'] as field}{#if trainee?.[field]}<h3>{label(field)}</h3><p>{trainee[field]}</p>{/if}{/each}</article><div class="detail-side"><div class="section-heading"><h2>{tr('Plans')}</h2><a href={`/plans/new?trainee=${trainee?.id}`}>＋ {tr('New plan')}</a></div>{#each recordsOf(trainee?.plans ?? trainee?.expand?.plans) as plan}<a class="compact-row" href={`/plans/${plan.id}`}><span class="type-dot"></span><span><strong>{plan.title ?? label(plan.type ?? 'Plan')}</strong><small>{tr(plan.type ?? 'Plan')} · {plan.status ?? '—'}</small></span><span>↗</span></a>{:else}<div class="empty">{tr('No records yet')}</div>{/each}{#if user?.role !== 'trainee'}<a class="button outline wide" href={`/progress-log/new/${trainee?.id}`}>{tr('Record assessment')}</a>{/if}<div class="section-heading"><h2>{tr('Progress assessment')}</h2></div>{#each recordsOf(trainee?.progress_logs) as log}<a class="compact-row" href={`/progress-log/${log.id}/edit`}><span><strong>{fmtDate(log.created ?? log.date)}</strong><small>{tr('Weight')}: {log.weight ?? '—'} kg · BMI {log.bmi ?? '—'}</small></span><span>↗</span></a>{:else}<div class="empty">{tr('No records yet')}</div>{/each}</div></div>
	</section>
{:else if /^\/coaches\/new$/.test(path) || /^\/coaches\/[^/]+\/edit$/.test(path)}
	{@const editing = path !== '/coaches/new'}{@const coach = editing ? resource : null}
	<section class="page narrow"><a class="backlink" href={editing ? `/coaches/${coach?.id}` : '/coaches'}>← {tr('Coaches')}</a><div class="page-heading"><span class="eyebrow">TEAM / COACHES</span><h1>{editing ? tr('Edit coach') : tr('New coach')}</h1><p>Invite a coach to work with your athletes.</p></div>{#if failure}<div class="notice error" role="alert">{failure}</div>{/if}
		<form method="POST" action="?/submit" use:enhance class="form-stack panel"><div class="two-col"><label>{tr('First name')}<input name="first_name" required maxlength="50" value={coach?.first_name ?? ''} /></label><label>{tr('Last name')}<input name="last_name" required maxlength="50" value={coach?.last_name ?? ''} /></label></div><label>{tr('Email')}<input name="email" type="email" required readonly={editing} value={coach?.email ?? ''} /></label><label>{tr('Phone')}<input name="phone" type="tel" value={coach?.phone ?? ''} /></label><div class="form-actions"><a class="button outline" href="/coaches">{tr('Cancel')}</a>{#if editing}<button class="button danger" type="submit" name="intent" value="delete" onclick={(event) => { if (!window.confirm('Delete this coach? This cannot be undone.')) event.preventDefault(); }}>{tr('Delete')}</button>{/if}<button class="button primary" type="submit">{editing ? tr('Save changes') : tr('Add coach')}</button></div></form>
	</section>
{:else if path === '/coaches'}
	<section class="page"><div class="page-heading split"><div><span class="eyebrow">PEOPLE / TEAM</span><h1>{tr('Coaches')}</h1><p>Manage the coaching team for this gym.</p></div><a class="button primary" href="/coaches/new">＋ {tr('Add coach')}</a></div><div class="records-list">{#each list as coach (coach.id)}<a class="person-row" href={`/coaches/${coach.id}`}><span class="person-mark">{fullName(coach).slice(0, 1)}</span><span class="person-main"><strong>{fullName(coach)}</strong><small>{coach.email ?? '—'} · {coach.phone ?? 'No phone'}</small></span><span class="row-meta">{coach.trainee_count ?? ''} {tr('Trainees')}</span><span class="row-arrow">↗</span></a>{:else}<div class="empty">{tr('No records yet')}<a href="/coaches/new">{tr('Add coach')}</a></div>{/each}</div>{#if pageCount(data.resource, 20) > 1}<nav class="pagination"><span>{data.resource?.total ?? list.length} records</span><div>{#each Array.from({ length: pageCount(data.resource, 20) }, (_, i) => i + 1) as current}<a class:current={current === Number(queryValue('page') || 1)} href={`?page=${current}`}>{current}</a>{/each}</div></nav>{/if}</section>
{:else if /^\/coaches\/[^/]+$/.test(path)}
	<section class="page"><a class="backlink" href="/coaches">← {tr('Coaches')}</a><div class="detail-heading"><span class="person-mark large">{fullName(resource).slice(0, 1)}</span><div><span class="eyebrow">COACH PROFILE</span><h1>{fullName(resource)}</h1><p>{resource?.email} {resource?.phone ? ` · ${resource.phone}` : ''}</p></div>{#if user?.role === 'owner'}<a class="button outline" href={`/coaches/${resource?.id}/edit`}>{tr('Edit')}</a>{/if}</div><div class="section-heading"><h2>{tr('Trainees')}</h2></div><div class="records-list">{#each recordsOf(resource?.trainees) as trainee}<a class="person-row" href={`/trainees/${trainee.id}`}><span class="person-mark">{fullName(trainee).slice(0, 1)}</span><span class="person-main"><strong>{fullName(trainee)}</strong><small>{trainee.email ?? '—'}</small></span><span class="row-arrow">↗</span></a>{:else}<div class="empty">{tr('No records yet')}</div>{/each}</div></section>
{:else if path === '/plans' || path === '/templates'}
	{@const templatesOnly = queryValue('is_template') === 'true' || path === '/templates'}
	<section class="page"><div class="page-heading split"><div><span class="eyebrow">PROGRAMMING / LIBRARY</span><h1>{templatesOnly ? tr('Plan templates') : tr('Plans')}</h1><p>Build, assign, and refine training programs.</p></div><a class="button primary" href={`/plans/new${templatesOnly ? '?template=true' : ''}`}>＋ {templatesOnly ? tr('New template') : tr('New plan')}</a></div><div class="tabs"><a class:active={!templatesOnly} href="/plans">{tr('Plans')}</a><a class:active={templatesOnly} href="/plans?is_template=true">{tr('Plan templates')}</a></div><form class="filter-bar" method="GET" action="/plans"><input type="hidden" name="is_template" value={templatesOnly ? 'true' : 'false'} /><label class="search-field"><span>⌕</span><input name="query" value={queryValue('query')} placeholder={`${tr('Search')} ${tr('Plans').toLowerCase()}`} /></label><select name="type" value={queryValue('type')}><option value="">{tr('Plan type')} · All</option><option value="training">{tr('Training')}</option><option value="diet">{tr('Diet')}</option><option value="steroid">{tr('Steroid')}</option></select>{#if user?.role === 'owner'}<select name="coach_id" value={queryValue('coach_id')}><option value="">{tr('Coach')} · All</option>{#each data.lists?.coaches ?? [] as coach}<option value={coach.id}>{fullName(coach)}</option>{/each}</select>{/if}<button class="button outline" type="submit">{tr('Filter')}</button></form><div class="records-list">{#each list as plan (plan.id)}<a class="plan-row" href={`/plans/${plan.id}`}><span class="plan-glyph">{(plan.type ?? 'P').slice(0, 1).toUpperCase()}</span><span class="person-main"><strong>{plan.template_name ?? plan.title ?? fullName(plan.expand?.trainee) ?? label(plan.type ?? 'Plan')}</strong><small>{tr(plan.type ?? 'Plan')} · {templatesOnly ? tr('Plan templates') : fullName(plan.expand?.trainee)} · {plan.coach_name ?? ''}</small></span><span class="tag">{plan.status ?? (templatesOnly ? 'Template' : '—')}</span><span class="row-arrow">↗</span></a>{:else}<div class="empty">{tr('No records yet')}<a href={`/plans/new${templatesOnly ? '?template=true' : ''}`}>{tr('Create plan')}</a></div>{/each}</div>{#if pageCount(data.resource) > 1}<nav class="pagination"><span>{data.resource?.total ?? list.length} records</span><div>{#each Array.from({ length: pageCount(data.resource) }, (_, i) => i + 1) as current}<a class:current={current === Number(queryValue('page') || 1)} href={`?${new URLSearchParams({ ...Object.fromEntries($page.url.searchParams), page: String(current) })}`}>{current}</a>{/each}</div></nav>{/if}</section>
{:else if /^\/plans\/new$/.test(path) || /^\/plans\/[^/]+\/edit$/.test(path)}
	{@const editing = path !== '/plans/new'}{@const plan = editing ? resource : null}{@const isTemplate = Boolean(data.isTemplate || plan?.is_template)}
	<section class="page narrow"><a class="backlink" href={editing ? `/plans/${plan?.id}` : '/plans'}>← {tr('Plans')}</a><div class="page-heading"><span class="eyebrow">PROGRAMMING / {isTemplate ? 'TEMPLATE' : 'PLAN'}</span><h1>{editing ? tr('Edit plan') : isTemplate ? tr('New template') : tr('New plan')}</h1><p>Start with the assignment details; add exercises after saving.</p></div>{#if failure}<div class="notice error" role="alert">{failure}</div>{/if}
		<form method="POST" action="?/submit" use:enhance class="form-stack panel"><input type="hidden" name="is_template" value={isTemplate ? 'true' : 'false'} />{#if isTemplate}<label>{tr('Template name')}<input name="template_name" maxlength="100" required value={plan?.template_name ?? ''} /></label>{/if}<label>{tr('Plan type')}<select name="type" value={plan?.type ?? 'training'}><option value="training">{tr('Training')}</option><option value="diet">{tr('Diet')}</option><option value="steroid">{tr('Steroid')}</option></select></label><label>{tr('Coach')}<select name="coach" value={plan?.coach ?? user?.id ?? ''}><option value={user?.id}>{fullName(user)}</option>{#each data.lists?.coaches ?? [] as coach}{#if coach.id !== user?.id}<option value={coach.id}>{fullName(coach)}</option>{/if}{/each}</select></label>{#if !isTemplate}<label>{tr('Trainee')}<select name="trainee" required value={plan?.trainee ?? $page.url.searchParams.get('trainee') ?? ''}><option value="">Choose a trainee</option>{#each data.lists?.trainees ?? [] as trainee}<option value={trainee.id}>{fullName(trainee)}</option>{/each}</select></label><div class="two-col"><label>{tr('Start date')}<input type="date" name="start_date" value={plan?.start_date?.slice(0, 10) ?? ''} /></label><label>{tr('End date')}<input type="date" name="end_date" value={plan?.end_date?.slice(0, 10) ?? ''} /></label></div>{/if}<div class="two-col"><label>{tr('Days per week')}<input type="number" name="days_per_week" min="1" max="7" value={plan?.days_per_week ?? 3} /></label><label>{tr('Status')}<select name="status" value={plan?.status ?? 'active'}><option value="active">{tr('Active')}</option><option value="inactive">{tr('Inactive')}</option></select></label></div><label>{tr('Notes')}<textarea name="notes" rows="3" maxlength="1000">{plan?.notes ?? ''}</textarea></label><div class="form-actions"><a class="button outline" href="/plans">{tr('Cancel')}</a>{#if editing}<button class="button danger" type="submit" name="intent" value="delete" onclick={(event) => { if (!window.confirm('Delete this plan? This cannot be undone.')) event.preventDefault(); }}>{tr('Delete')}</button>{/if}<button class="button primary" type="submit">{editing ? tr('Save changes') : tr('Create plan')}</button></div></form>
	</section>
{:else if /^\/templates\/[^/]+\/apply$/.test(path)}
	<section class="page narrow"><a class="backlink" href={`/plans/${resource?.id}`}>← {tr('Plan templates')}</a><div class="page-heading"><span class="eyebrow">TEMPLATE / ASSIGN</span><h1>{tr('Apply to trainee')}</h1><p>{resource?.template_name ?? resource?.title ?? tr('Plan templates')}</p></div>{#if failure}<div class="notice error" role="alert">{failure}</div>{/if}<form method="POST" action="?/submit" use:enhance class="form-stack panel"><label>{tr('Trainee')}<select name="trainee" required><option value="">Choose a trainee</option>{#each data.lists?.trainees ?? [] as trainee}<option value={trainee.id}>{fullName(trainee)}</option>{/each}</select></label><label>{tr('Coach')}<select name="coach" value={user?.id}>{#each data.lists?.coaches ?? [] as coach}<option value={coach.id}>{fullName(coach)}</option>{/each}</select></label><div class="two-col"><label>{tr('Start date')}<input type="date" name="start_date" /></label><label>{tr('End date')}<input type="date" name="end_date" /></label></div><label>{tr('Notes')}<textarea name="notes" rows="3"></textarea></label><button class="button primary" type="submit">{tr('Apply to trainee')}</button></form></section>
{:else if /^\/plans\/[^/]+$/.test(path)}
	{@const plan = resource}{@const items = getResourceItems(plan)}{@const isTemplate = Boolean(plan?.is_template)}
	<section class="page"><a class="backlink" href="/plans">← {tr('Plans')}</a><div class="detail-heading"><span class="plan-glyph large-glyph">{(plan?.type ?? 'P').slice(0, 1).toUpperCase()}</span><div><span class="eyebrow">{isTemplate ? tr('Plan templates') : tr('Plans')}</span><h1>{plan?.template_name ?? plan?.title ?? fullName(plan?.expand?.trainee)}</h1><p>{tr(plan?.type ?? 'Plan')} · {plan?.status ?? '—'}</p></div><a class="button outline" href={`/plans/${plan?.id}/edit`}>{tr('Edit')}</a></div>
		<div class="detail-grid"><article class="panel"><span class="eyebrow">PROGRAM DETAILS</span><dl><dt>{tr('Coach')}</dt><dd>{fullName(plan?.expand?.coach) || plan?.coach_name || '—'}</dd>{#if !isTemplate}<dt>{tr('Trainee')}</dt><dd>{fullName(plan?.expand?.trainee) || plan?.trainee_name || '—'}</dd><dt>{tr('Start date')}</dt><dd>{fmtDate(plan?.start_date)}</dd><dt>{tr('End date')}</dt><dd>{fmtDate(plan?.end_date)}</dd>{/if}<dt>{tr('Days per week')}</dt><dd>{plan?.days_per_week ?? '—'}</dd></dl>{#if plan?.notes}<p>{plan.notes}</p>{/if}{#if isTemplate}<a class="button primary wide" href={`/templates/${plan?.id}/apply`}>{tr('Apply to trainee')}</a>{/if}</article><div><div class="section-heading"><h2>{tr('Plan items')}</h2><a href={`/items/new?plan_type=${plan?.type}&plan_id=${plan?.id}`}>＋ {tr('Add item')}</a></div><div class="item-list">{#each items as item (item.id)}<article class="item-row"><div><span class="eyebrow">{plan?.type === 'training' ? `${tr('Training')} · ${tr('Day')} ${item.seq ?? 1}` : tr(plan?.type ?? 'Plan')}</span><h3>{item.name ?? item.item_name ?? item.meal_name ?? '—'}</h3><p>{#if plan?.type === 'training'}{item.sets ?? '—'} sets · {item.reps ?? '—'} reps · {item.weight ?? '—'} kg{:else if plan?.type === 'diet'}{item.quantity ?? ''}{:else}{item.dosage ?? item.frequency ?? ''}{/if}</p>{#if item.notes}<small>{item.notes}</small>{/if}</div><div class="item-actions"><a href={`/items/${item.id}/edit?plan_type=${plan?.type}`}>{tr('Edit')}</a><form method="POST" action={`/items/${item.id}?/submit`} use:enhance><input type="hidden" name="intent" value="delete" /><input type="hidden" name="plan" value={plan?.id} /><input type="hidden" name="plan_type" value={plan?.type} /><button class="link-danger" type="submit" onclick={(event) => { if (!window.confirm('Delete this item?')) event.preventDefault(); }}>{tr('Delete')}</button></form></div></article>{:else}<div class="empty">{tr('No records yet')}<a href={`/items/new?plan_type=${plan?.type}&plan_id=${plan?.id}`}>{tr('Add item')}</a></div>{/each}</div></div></div>
	</section>
{:else if path === '/items/new' || /^\/items\/[^/]+\/edit$/.test(path)}
	{@const editing = path !== '/items/new'}{@const item = editing ? resource : null}{@const type = planType(item)}{@const planId = item?.plan ?? $page.url.searchParams.get('plan_id') ?? ''}
	<section class="page narrow"><a class="backlink" href={`/plans/${planId}`}>← {tr('Plans')}</a><div class="page-heading"><span class="eyebrow">PROGRAMMING / ITEM</span><h1>{editing ? tr('Edit item') : tr('Add item')}</h1><p>{tr(type)} · {resource?.title ?? resource?.template_name ?? ''}</p></div>{#if failure}<div class="notice error" role="alert">{failure}</div>{/if}<form method="POST" action="?/submit" use:enhance class="form-stack panel"><input type="hidden" name="plan_type" value={type} /><input type="hidden" name="plan" value={planId} />
			{#if type === 'training'}<label>{tr('Exercise')}<input name="item_name" required value={item?.name ?? ''} /></label><div class="three-col"><label>{tr('Day')}<input type="number" name="seq" min="1" value={item?.seq ?? 1} /></label><label>{tr('Sets')}<input type="number" name="sets" min="1" value={item?.sets ?? ''} /></label><label>{tr('Reps')}<input type="number" name="reps" min="1" value={item?.reps ?? ''} /></label></div><div class="two-col"><label>{tr('Weight')} (kg)<input type="number" name="weight" min="0" step="0.5" value={item?.weight ?? ''} /></label><label>{tr('Rest')} (sec)<input type="number" name="rest_seconds" min="0" value={item?.rest_seconds ?? ''} /></label></div><label>{tr('Category')}<input name="category" value={item?.category ?? ''} /></label>
			{:else if type === 'diet'}<label>{tr('Meal')}<input name="meal_name" required value={item?.meal_name ?? ''} /></label><label>{tr('Food')}<input name="food_name" required value={item?.name ?? ''} /></label><label>{tr('Quantity')}<input name="quantity" value={item?.quantity ?? ''} /></label><label>{tr('Day')}<input type="number" name="seq" min="1" value={item?.seq ?? 1} /></label>
			{:else}<label>{tr('Name')}<input name="name" required value={item?.name ?? ''} /></label><label>{tr('Type')}<input name="type" value={item?.type ?? ''} /></label><label>{tr('Dosage')}<input name="dosage" value={item?.dosage ?? ''} /></label><label>{tr('Frequency')}<input name="frequency" value={item?.frequency ?? ''} /></label><label>{tr('Day')}<input type="number" name="seq" min="1" value={item?.seq ?? 1} /></label>{/if}<label>{tr('Notes')}<textarea name="notes" rows="3" maxlength="1000">{item?.notes ?? ''}</textarea></label><div class="form-actions"><a class="button outline" href={`/plans/${planId}`}>{tr('Cancel')}</a>{#if editing}<button class="button danger" type="submit" name="intent" value="delete" onclick={(event) => { if (!window.confirm('Delete this item?')) event.preventDefault(); }}>{tr('Delete')}</button>{/if}<button class="button primary" type="submit">{tr('Save')}</button></div></form></section>
{:else if /^\/progress-log\/new\/[^/]+$/.test(path) || /^\/progress-log\/[^/]+\/edit$/.test(path)}
	{@const logEdit = path.includes('/edit')}{@const log = logEdit ? resource : null}{@const trainee = logEdit ? resource?.trainee_record : resource}{@const logTrainee = resource?.expand?.trainee ?? trainee}
	<section class="page narrow"><a class="backlink" href={logTrainee?.id ? `/trainees/${logTrainee.id}` : '/trainees'}>← {tr('Trainees')}</a><div class="page-heading"><span class="eyebrow">MEASURE / TRACK</span><h1>{logEdit ? tr('Edit assessment') : tr('Progress assessment')}</h1><p>{fullName(logTrainee)}</p></div>{#if failure}<div class="notice error" role="alert">{failure}</div>{/if}<form method="POST" action="?/submit" use:enhance enctype="multipart/form-data" class="form-stack panel"><input type="hidden" name="trainee" value={logTrainee?.id ?? path.split('/').at(-1)} /><div class="two-col"><label>{tr('Height')} (cm)<input type="number" name="height" min="30" max="300" step="0.1" required value={log?.height ?? ''} /></label><label>{tr('Weight')} (kg)<input type="number" name="weight" min="20" max="500" step="0.1" required value={log?.weight ?? ''} /></label></div><div class="three-col">{#each ['chest', 'waist', 'hip', 'arms', 'bmi', 'bfp', 'bmr', 'tdee', 'lbm', 'whr'] as metric}<label>{label(metric)}<input type="number" name={metric} min="0" step="0.1" value={log?.[metric] ?? ''} /></label>{/each}</div><label>{tr('Notes')}<textarea name="notes" rows="3" maxlength="1000">{log?.notes ?? ''}</textarea></label><label>{tr('Progress photos')}<input type="file" name="progress_photos" accept="image/jpeg,image/png,image/webp,image/gif" multiple /></label><div class="form-actions"><a class="button outline" href={logTrainee?.id ? `/trainees/${logTrainee.id}` : '/trainees'}>{tr('Cancel')}</a><button class="button primary" type="submit">{tr('Record assessment')}</button></div></form></section>
{:else if path === '/user/dashboard' || path === '/user/plans' || /^\/user\/plans\/[^/]+$/.test(path)}
	{@const userPlans = path === '/user/dashboard' ? (resource?.plans ?? {}) : resource}{@const detail = /^\/user\/plans\/[^/]+$/.test(path)}{@const allPlans = Array.isArray(userPlans) ? userPlans : Object.values(userPlans ?? {}).flatMap((value: any) => recordsOf(value))}
	<section class="page"><div class="page-heading split"><div><span class="eyebrow">YOUR TRAINING / GYME</span><h1>{detail ? (resource?.title ?? tr('Plans')) : path === '/user/dashboard' ? `${tr('Welcome back')}${user?.first_name ? `, ${user.first_name}` : ''}` : tr('Your plans')}</h1><p>{detail ? tr(resource?.type ?? 'Plan') : 'Your coach’s plan, ready when you are.'}</p></div>{#if !detail}<a class="button outline" href="/user/profile">{tr('Profile')}</a>{/if}</div>
		{#if detail}<div class="detail-grid"><article class="panel"><span class="eyebrow">{tr('Plan type')}</span><h2>{tr(resource?.type ?? 'Plan')}</h2><dl><dt>{tr('Start date')}</dt><dd>{fmtDate(resource?.start_date)}</dd><dt>{tr('End date')}</dt><dd>{fmtDate(resource?.end_date)}</dd><dt>{tr('Days per week')}</dt><dd>{resource?.days_per_week ?? '—'}</dd></dl></article><div class="item-list">{#each getResourceItems(resource) as item}<article class="item-row"><div><span class="eyebrow">{tr('Day')} {item.seq ?? 1}</span><h3>{item.name ?? item.meal_name ?? '—'}</h3><p>{item.sets ? `${item.sets} sets · ${item.reps} reps` : item.quantity ?? item.dosage ?? ''}</p></div></article>{/each}<form method="POST" action={`/user/plans/${resource?.id}/done?/submit`} use:enhance><button class="button primary wide" type="submit">{tr('Complete this day')} <span aria-hidden="true">↗</span></button></form></div></div>
		{:else}<div class="plan-categories">{#each ['training', 'diet', 'steroid'] as category}{@const entries = recordsOf((userPlans as any)?.[category])}<section><div class="section-heading"><h2>{tr(category === 'steroid' ? 'Steroid' : category.charAt(0).toUpperCase() + category.slice(1))}</h2><span>{entries.length}</span></div>{#each entries as plan (plan.id)}<a class="assignment-card" href={`/user/plans/${plan.id}`}><span class="plan-glyph">{category.slice(0, 1).toUpperCase()}</span><span><strong>{plan.title ?? plan.name ?? tr(category)}</strong><small>{fmtDate(plan.start_date)} – {fmtDate(plan.end_date)}</small></span><span class="row-arrow">↗</span></a>{:else}<div class="empty">{tr('No records yet')}</div>{/each}</section>{/each}</div>{/if}
	</section>
{:else if path === '/profile' || path === '/user/profile'}
	{@const person = resource?.user ?? resource}
	<section class="page narrow"><div class="page-heading"><span class="eyebrow">ACCOUNT / PERSONAL</span><h1>{tr('Profile')}</h1><p>Keep your contact details up to date.</p></div>{#if failure}<div class="notice error" role="alert">{failure}</div>{/if}<form method="POST" action="?/submit" use:enhance class="form-stack panel"><div class="two-col"><label>{tr('First name')}<input name="first_name" required value={person?.first_name ?? ''} /></label><label>{tr('Last name')}<input name="last_name" required value={person?.last_name ?? ''} /></label></div><label>{tr('Email')}<input name="email" type="email" value={person?.email ?? ''} readonly /></label><label>{tr('Phone')}<input name="phone" type="tel" value={person?.phone ?? ''} /></label><div class="form-actions"><a class="button outline" href="/change-password">{tr('Change password')}</a><button class="button primary" type="submit">{tr('Save changes')}</button></div></form></section>
{:else}
	<section class="page state-page"><span class="state-mark">?</span><h1>Page not found</h1><p>This part of the coaching space doesn’t exist.</p><a class="button primary" href={user?.role === 'trainee' ? '/user/dashboard' : '/dashboard'}>{tr('Dashboard')}</a></section>
{/if}
